//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_ver.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string UserName { get; set; }
        public int MaSP { get; set; }
        public int SL { get; set; }
        public Nullable<decimal> SumAll { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
