//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_ver.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help
    {
        public string UserName { get; set; }
        public string LinhVuc { get; set; }
        public string INFO { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
