//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_ver.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string Loai { get; set; }
        public string Spec { get; set; }
        public string NhaSX { get; set; }
        public int SLKho { get; set; }
        public decimal GiaTien { get; set; }
        public int GiamGia { get; set; }
    
        public virtual CungCap CungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
